import { ExternalTokenizer, ContextTracker, LRParser } from '@lezer/lr';
import { styleTags, tags } from '@lezer/highlight';

// This file was generated by lezer-generator. You probably shouldn't edit it.
var Line = 1, keyShort = 2, keyText = 3, keyDict = 4, keyList = 5, eol = 26, eq = 27, dedent = 28, indentT = 29, indentD = 30, indentL = 31, margin$1 = 32;

/******************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
/* global Reflect, Promise, SuppressedError, Symbol, Iterator */


var __assign = function() {
    __assign = Object.assign || function __assign(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p)) t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};

typeof SuppressedError === "function" ? SuppressedError : function (error, suppressed, message) {
    var e = new Error(message);
    return e.name = "SuppressedError", e.error = error, e.suppressed = suppressed, e;
};

var prototypes = [];
function hashAfterInstallingPrototype(context) {
    var parent = context.parent;
    if (parent === null)
        return 0;
    if (parent.depth === Number.MAX_SAFE_INTEGER)
        // very unlikely to get here because memory would have been filled up
        throw new RangeError("can't go deeper than MAX_SAFE_INTEGER");
    var length = 3 * (parent.depth + 1);
    while (prototypes.length < length) {
        var depth = (1 + Math.floor(prototypes.length / 3)) | 0;
        var meta = { depth: depth, sealed: false };
        prototypes.push(Object.setPrototypeOf(__assign({}, meta), Text.prototype));
        prototypes.push(Object.setPrototypeOf(__assign({}, meta), Dict.prototype));
        prototypes.push(Object.setPrototypeOf(meta, List.prototype));
    }
    switch (Object.getPrototypeOf(context)) {
        case Text.prototype:
            Object.setPrototypeOf(context, prototypes[length - 3]);
            break;
        case Dict.prototype:
            Object.setPrototypeOf(context, prototypes[length - 2]);
            break;
        case List.prototype:
            Object.setPrototypeOf(context, prototypes[length - 1]);
            break;
    }
    var hash = 17; // emulates java.util.Objects.hash()
    hash = (31 * hash + parent.hash) | 0;
    hash = (31 * hash + context.depth) | 0;
    return hash;
}
function sealPrototype(context) {
    if (context.sealed)
        return context;
    var proto = Object.create(Object.getPrototypeOf(context));
    proto.sealed = true;
    var clone = Object.assign(Object.create(proto), context);
    clone.hash = (31 * context.hash + 127) | 0; // emulates annotation (kinda)
    return clone;
}
var File = /** @class */ (function () {
    function File() {
        this.parent = null;
        this.hash = 0;
        this.depth = 0;
        var meta = { depth: 0, sealed: false };
        var proto = Object.setPrototypeOf(meta, File.prototype);
        Object.setPrototypeOf(this, proto);
    }
    File.prototype.toString = function () {
        return "".concat(this.sealed ? "s" : "", "F");
    };
    File.prototype.seal = function () {
        return sealPrototype(this);
    };
    return File;
}());
var Text = /** @class */ (function () {
    function Text(parent) {
        this.parent = parent;
        this.hash = hashAfterInstallingPrototype(this);
    }
    Text.prototype.toString = function () {
        return "".concat(this.sealed ? "s" : "", "T").concat(this.depth);
    };
    Text.prototype.seal = function () {
        return sealPrototype(this);
    };
    return Text;
}());
var Dict = /** @class */ (function () {
    function Dict(parent) {
        this.parent = parent;
        var hash = hashAfterInstallingPrototype(this);
        hash = (31 * hash + 1231) | 0; // emulates a true
        this.hash = hash;
    }
    Dict.prototype.toString = function () {
        return "".concat(this.sealed ? "s" : "", "D").concat(this.depth);
    };
    Dict.prototype.seal = function () {
        return sealPrototype(this);
    };
    return Dict;
}());
var List = /** @class */ (function () {
    function List(parent) {
        this.parent = parent;
        var hash = hashAfterInstallingPrototype(this);
        hash = (31 * hash + 1237) | 0; // emulates a false
        this.hash = hash;
    }
    List.prototype.toString = function () {
        return "".concat(this.sealed ? "s" : "", "L").concat(this.depth);
    };
    List.prototype.seal = function () {
        return sealPrototype(this);
    };
    return List;
}());

var EOF$1 = -1, TAB = 9, LF = 10, HASH = 35, SLASH = 47;
var EQ = 61, A_KET = 62, S_KET = 93, C_KET = 125;
var RESERVED = [HASH, SLASH, EQ, 64 /*@*/, 60, A_KET, 91, S_KET, 123, C_KET];
var tokenizer = new ExternalTokenizer(function (input, stack) {
    var context = stack.context;
    var depth = context.depth;
    var previous = input.peek(-1);
    var edge = previous === LF || previous === EOF$1;
    scan: {
        // some `break scan` are intentional dead code acting as documentation.
        // the grammar is atypical, so this code does more than most tokenizers.
        // could (arguably should) push some of this up into the grammar, but
        // that would make it harder to read and thus much less pedagogical.
        if (edge && input.next === LF) {
            input.advance();
            while (input.next === LF)
                input.advance();
            input.acceptToken(margin$1);
            break scan;
        }
        if (edge && depth !== 0 && input.next !== TAB) {
            if (stack.canShift(dedent))
                input.acceptTokenTo(dedent, stack.pos); // zero-width
            break scan;
        }
        if (edge && depth !== 0 && input.next === TAB) {
            for (input.advance(); input.pos < stack.pos + depth; input.advance())
                if (input.next !== TAB) {
                    if (stack.canShift(dedent))
                        input.acceptTokenTo(dedent, stack.pos); // zero-width
                    break scan;
                }
            input.acceptToken(margin$1);
            // next call can indent if TAB follows margin
            break scan;
        }
        if (input.next === TAB) {
            if (stack.canShift(indentT)) {
                input.acceptToken(indentT, 1);
                break scan;
            }
            if (stack.canShift(indentD)) {
                input.acceptToken(indentD, 1);
                break scan;
            }
            if (stack.canShift(indentL)) {
                input.acceptToken(indentL, 1);
                break scan;
            }
            // could also be Line...
        }
        if (!edge && !context.sealed && stack.canShift(Line)) {
            // TODO perhaps completely empty lines can be ListLines instead of margin?
            // TODO consider allowing SLASH as long as it isn't SLASH SLASH
            // makes a lot of sense here, less sense in KeyShort but maybe there too
            if (context instanceof List && RESERVED.includes(input.next))
                ;
            else
                for (;; input.advance())
                    if (input.next === LF) {
                        input.acceptToken(Line, 1);
                        break scan;
                    }
                    else if (input.next === EOF$1) {
                        input.acceptToken(Line);
                        break scan;
                    }
        }
        if ((edge && depth !== 0 || input.next === EOF$1) && stack.canShift(dedent)) {
            input.acceptToken(dedent);
            break scan;
        }
        if (stack.canShift(keyText)) {
            for (var prev = false;; input.advance())
                if (input.next === LF || input.next === EOF$1) {
                    input.acceptToken(keyText, prev ? -1 : 0);
                    break scan;
                }
                else
                    prev = (input.next === A_KET);
            break scan;
        }
        if (stack.canShift(keyDict)) {
            for (var prev = false;; input.advance())
                if (input.next === LF || input.next === EOF$1) {
                    input.acceptToken(keyDict, prev ? -1 : 0);
                    break scan;
                }
                else
                    prev = (input.next === C_KET);
            break scan;
        }
        if (stack.canShift(keyList)) {
            for (var prev = false;; input.advance())
                if (input.next === LF || input.next === EOF$1) {
                    input.acceptToken(keyList, prev ? -1 : 0);
                    break scan;
                }
                else
                    prev = (input.next === S_KET);
            break scan;
        }
        if (stack.canShift(eol)) {
            if (input.next === LF)
                input.acceptToken(eol, 1);
            else if (input.next === EOF$1)
                // grammar wants an eol before the eof
                input.acceptToken(eol);
            // keep going
        }
        if (stack.canShift(eq) && input.next === EQ) {
            input.acceptToken(eq, 1);
            break scan;
        }
        if (stack.canShift(keyShort)) {
            if (input.next !== EQ && RESERVED.includes(input.next))
                ;
            else
                for (; input.next !== EOF$1; input.advance())
                    if (input.next === EQ) {
                        input.acceptToken(keyShort);
                        break scan;
                    }
        }
    } // end scan
});

var EOF = -1;
var margin = new ContextTracker({
    start: new File(),
    hash: function (context) { return context.hash; },
    shift: function (context, term, stack, input) {
        var move = undefined;
        if (term === dedent) {
            var parent_1 = context.parent;
            if (parent_1 === null)
                ;
            else if (context.sealed && !parent_1.sealed)
                move = parent_1.seal();
            else
                move = parent_1;
        }
        else if (context.sealed)
            ;
        else if (term === indentT)
            move = new Text(context);
        else if (term === indentD)
            move = new Dict(context);
        else if (term === indentL)
            move = new List(context);
        if (input.peek(stack.pos - input.pos) === EOF)
            move = (move !== null && move !== void 0 ? move : context).seal();
        return move !== null && move !== void 0 ? move : context;
    }
});

var highlight = styleTags({
    '# "#!" "//" @': tags.keyword,
    "< <> >": tags.angleBracket,
    "{ {} }": tags.brace,
    "[ [] ]": tags.squareBracket,
    "Shebang/Line": tags.documentMeta,
    "Prolog/Line Epilog/Line Comment/Line": tags.comment,
    "Text/Line": tags.string,
    "Key/Line": tags.namespace,
});

// This file was generated by lezer-generator. You probably shouldn't edit it.
var parser = LRParser.deserialize({
    version: 14,
    states: ",xQnQROOOuQPO'#CcOzQPO'#CdO!PQPO'#CfOOQP'#Cq'#CqO!UQPO'#DSO!ZQPO'#DSO!`QPO'#DSO!eQPO'#DSO!jQPO'#DSO!oQRO'#CeO#^QRO'#CeOOQP'#Cs'#CsQ#oQROOQ#oQROOQVQROOO#vQRO,58}O$eQRO,59OO%SQRO,59QOOQP'#Cg'#CgO%hQRO,59nOOQP'#Ci'#CiO%mQRO,59nOOQP'#Ck'#CkO%rQRO,59nO%wQTO,59nO&VQPO,59nO&[QPO'#CoOOQP,59P,59PO&aQRO,59POOQP-E6q-E6qO'OQPO'#DPOOQP1G.i1G.iOOQP1G.j1G.jOOQP1G.l1G.lO'WQPO1G/YO']QPO1G/YO'bQPO1G/YOOQP'#Cp'#CpO'gQTO1G/YOOQP'#Cn'#CnOOQP1G/Y1G/YO$eQRO,59ZOOQP1G.k1G.kOOQP'#Cr'#CrO'rQPO,59kOOQP,59k,59kO'zQRO7+$tO(RQRO7+$tO(sQRO7+$tO)eQPO'#DZO)jQPO'#DZO)oQPO'#DZOOQP7+$t7+$tOOQP1G.u1G.uOOQP-E6p-E6pOOQP1G/V1G/VOOQP'#Ch'#ChOOQP<<H`<<H`O)tQRO'#CjO){QTO'#ClO'zQRO,59uO(RQRO,59uO(sQRO,59uOOQP,59U,59UO*aQRO,59UO*aQRO,59UO*kQTO'#CmOOQP'#Ct'#CtO+PQTO,59WOOQP,59W,59WO+PQTO,59WOOQP1G/a1G/aOOQP1G.p1G.pO+bQRO1G.pO+lQTO,59OO,QQTO,59uO,XQTO,59uO,pQTO,59uOOQP,59X,59XOOQP-E6r-E6rOOQP1G.r1G.rO-XQTO1G.rOOQP7+$[7+$[O+lQTO,59ZOOQP7+$^7+$^O-jQPO'#CdO-oQPO'#CoO-tQPO'#DZO-yQPO'#DZO.OQPO'#DZ",
    stateData: ".T~OpOS~OQSOtQOuROwTOyUO{VO!RWO~OrPO~PVOP`O~OPaO~OPbO~ORcO~OSeO~OTgO~OjiO~OkjO~OtkOQXXiXXuXXwXXyXX{XX!RXXlXX~OQSOwTOyUO{VO!RWO~OuRO~P#^OmoOQsPisPtsPusPwsPysP{sP!RsP~OmoOQsPisPusPwsPysP{sP!RsPlsP~OmoOQsPwsPysP{sP!RsP~OxsO~OztO~O|uO~OmoO!OsP!PsP!QsP~OPxO~OPzO~OtkOQXaiXauXawXayXa{Xa!RXalXa~OP|Ol!OO~Oj!PO~Oj!QO~Oj!RO~O!O!SO!P!TO!Q!UO~OP|Ol!YO~OlsP~P#vOn!]OQ^Pi^Pt^Pu^Pw^Py^P{^P!R^Pl^P~Oo!^OQ`Pi`Pt`Pu`Pw`Py`P{`P!R`Pl`P~Oj!_O~Oj!`O~Oj!aO~Ol!bO~PVOPxOl!hOt!xO!O!zO!P!{O!Q!|O~Ol!kOuRO~P#^Ot!yOPaXlaX!OaX!PaX!QaX~OPxOl!sO!O!zO!P!{O!Q!|O~Ol!uOuRO~P#^OmoOPsPlsP!OsP!PsP!QsP~OtsP~P+lOn!]OP^Pl^Pt^P!O^P!P^P!Q^P~Oo!^OP`Pl`Pt`P!O`P!P`P!Q`P~OPxOl!wO!O!zO!P!{O!Q!|O~OP!mO~OP!vO~Oj!nO~Oj!oO~Oj!pO~O",
    goto: "%x!OPPPPPPP!P!S!^!h!r!u!|#P#W#Z#b#h#q#z#}$Y$`$pPPPPPPPPPP$zPP%bPPPPPP%oR_OS^O_Q!d!]R!i!^a[O]^_!]!c!d!laZO]^_!]!c!d!lRdTQ![!PT!j!_!nRfUQ![!QT!j!`!oRhVQ![!RT!j!a!pX!f!^!g!i!tQyjX!e!^!g!i!tQlYQ{mR!q!eRwicXOZ]^_!]!c!d!lQ}oR!X}U]O^_Un]!c!lQ!c!]R!l!dQ!g!^S!r!g!tR!t!iQp`Sqa!mQrbQviS!Wz!vV!Z!P!_!n`YO]^_!]!c!d!lRmZQ!VwX!e!^!g!i!t",
    nodeNames: "⚠ Line Line Line Line Line File Shebang Prolog Entry Comment Key Text Key Dict Key List Item Text Epilog Key Key",
    maxTerm: 49,
    context: margin,
    propSources: [highlight],
    skippedNodes: [0],
    repeatNodeCount: 3,
    tokenData: "#e~RXstn!P!Q{!^!_!W!`!a!e!b!c!j!}#O!o#P#Q!|#o#p#R#q#r#`~sPt~qrv~{Or~~!OP!P!Q!R~!WOu~R!]PwP!`!a!`Q!eO!OQ~!jOx~~!oO!R~R!tP{P#P#Q!wQ!|O!QQ~#RO|~R#WPyP#q#r#ZQ#`O!PQ~#eOz~",
    tokenizers: [tokenizer, 0, 1],
    topRules: { "File": [0, 6] },
    tokenPrec: 0,
    termNames: { "0": "⚠", "1": "Line", "2": "keyShort", "3": "keyText", "4": "keyDict", "5": "keyList", "6": "@top", "7": "Shebang", "8": "Prolog", "9": "Entry", "10": "Comment", "11": "KeyText", "12": "Text", "13": "KeyDict", "14": "Dict", "15": "KeyList", "16": "List", "17": "Item", "18": "OneLine", "19": "Epilog", "20": "Key", "21": "KeyShort", "22": "Line+", "23": "Entry+", "24": "Item+", "25": "␄", "26": "eol", "27": "eq", "28": "dedent", "29": "indentT", "30": "indentD", "31": "indentL", "32": "margin", "33": "%mainskip", "34": "\"#!\"", "35": "text", "36": "\"#\"", "37": "\"//\"", "38": "keyValue", "39": "\"<\"", "40": "\">\"", "41": "\"{\"", "42": "\"}\"", "43": "\"[\"", "44": "\"]\"", "45": "value", "46": "\"<>\"", "47": "\"{}\"", "48": "\"[]\"", "49": "\"@\"" }
});

export { parser };
