// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {leftEdge} from "./external.ts"
import {peekTabs} from "./context.ts"
export const parser = LRParser.deserialize({
  version: 14,
  states: ",fOQOPOOQVOROOObOSO'#C^OgOWO'#C_OrOPO'#CaOwOPO'#C`OOOP'#Ch'#ChQ|OROOQOOOOOQ|OROOQ!UOROOO!^OPO'#CqOOOP,58x,58xObOSO,58yObOSO,58|O!cOWO,58{O!hOQO,58{O!mOQO'#CwOOOP,58z,58zOjOQO'#CbOOOP-E6f-E6fO!xOPO,59]OOOP1G.e1G.eOOOP1G.h1G.hO#QOPO1G.gO#VOWO1G.gO#[OWO,59cO#aOWO,59cO#fOWO,59cO#kOSO'#CgO#pOPO1G.wOOOP1G.w1G.wO#xOPO7+$RO$QOPO7+$RO$VOPO1G.}O$[OPO1G.}O$aOPO1G.}O$fOPO,59ROOOP-E6e-E6eOOOP7+$c7+$cO$kOPO<<GmOOOP<<Gm<<GmO$kOPO<<GmO$sOPO'#CcOOOP7+$i7+$iO%OOPO'#CeO%ZOPO'#CfOOOP1G.m1G.mOOOPAN=XAN=XO%fOPOAN=XO%nOSO'#CgO%vOPO,58}O&ROSO'#CdOOOP,58},58}O&WOPO,58}O%vOPO,58}OOOP,59P,59PO&]OPO,59PO&bOPO,59PO&bOPO,59PO&mOWO'#C_OOOP'#Ci'#CiO&{OPO,59QOOOP,59Q,59QO'WOPO,59QO&{OPO,59QOOOPG22sG22sOOOP1G.i1G.iO']OPO1G.iObOSO,59OO'bOPO1G.iOOOP1G.k1G.kO'mOPO1G.kO'rOPO1G.kOOOP-E6g-E6gOOOP1G.l1G.lO'}OPO1G.lO(SOPO1G.lOOOP7+$T7+$TOOOP1G.j1G.jO(_OPO7+$TOOOP7+$V7+$VO(dOPO7+$VOOOP7+$W7+$WO(iOPO7+$WOOOP<<Go<<GoOOOP<<Gq<<GqOOOP<<Gr<<Gr",
  stateData: "(n~O_PO~OcROdQOoWO~OfZO~Og]Oh^Oi_O~Oc`O~OcaO~OccOoWO~OcROoWO~O`eO~OjhO~OiiO~OljOmkOnlO~OaoOcmO~O`pO~OjqO~OjrO~OjsO~OjtO~OfuO~OawOcmO~OayOcmO~O`zO~O`{O~O`}O~O`!OO~O_!PO~Oa!QOcmO~Oa!VOb!UOc!SO~Oa!YOb!UOcRO~Oa!aOb!UOc!^O~Oa!dOcmO~OfuOg]O~Oa!eOb!UOcmO~Og!gO~Oa!eO~Oa!iO~Oa!iOb!UOccO~Og]OljOmkOnlO~Oa!mOb!UOcaO~Oa!mO~Oa!pO~Oa!pOb!UOcmO~Oa!sO~Oa!sOb!UOccO~Oa!uO~Oa!uOb!UOcaO~Oa!wO~Oa!xO~Oa!yO~O",
  goto: "$}lPPmp}!X!c!m!p#`#c#f#|$^PPPPPPP$hPPPPP$tRYPSXPYQ!X{Q!]}R!c!OaUPVXY}![!]!kaTPVXY}![!]!kaSPVXY}![!]!kR|rQ!W{Q!Z}Q!b!OS!f!T!XS!j![!]S!n!`!cQ!r!hQ!t!kR!v!oR|sR|tQneYvnx!R!T!hQxpQ!RzQ!T{R!h!XUVPXYUdV![!kQ![}R!k!]Q!`!OS!l!`!oR!o!cQ[QQf]Qg^R!q!gQbTX!_!O!`!c!o",
  nodeNames: "⚠ File Shebang Prolog Entry Key Comment Text Epilog Dict List",
  maxTerm: 31,
  context: peekTabs,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "*TVRcOY!^YZ#RZs!^st#[t!P!^!P!Q$h!Q!^!^!^!_%r!_!b!^!b!c&|!c!}!^!}#O'h#O#o!^#o#p(r#p;'S!^;'S;=`!{<%l~!^~O!^~~)|Q!aVOY!^YZ!vZ;'S!^;'S;=`!{<%l~!^~O!^~~!vQ!{OfQQ#OP;=`<%l!^V#[OoPjSfQV#aXgUOY!^YZ!vZq!^qr#|r;'S!^;'S;=`!{<%l~!^~O!^~~!vR$RVdPOY!^YZ!vZ;'S!^;'S;=`!{<%l~!^~O!^~~!vV$kXOY!^YZ!vZ!P!^!P!Q%W!Q;'S!^;'S;=`!{<%l~!^~O!^~~!vV%]VhTOY!^YZ!vZ;'S!^;'S;=`!{<%l~!^~O!^~~!vV%uXOY!^YZ!vZ!`!^!`!a&b!a;'S!^;'S;=`!{<%l~!^~O!^~~!vV&gVlTOY!^YZ!vZ;'S!^;'S;=`!{<%l~!^~O!^~~!vV'RViTOY!^YZ!vZ;'S!^;'S;=`!{<%l~!^~O!^~~!vV'kXOY!^YZ!vZ#P!^#P#Q(W#Q;'S!^;'S;=`!{<%l~!^~O!^~~!vV(]VnTOY!^YZ!vZ;'S!^;'S;=`!{<%l~!^~O!^~~!vV(uXOY!^YZ!vZ#q!^#q#r)b#r;'S!^;'S;=`!{<%l~!^~O!^~~!vV)gVmTOY!^YZ!vZ;'S!^;'S;=`!{<%l~!^~O!^~~!vU*TOjSfQ",
  tokenizers: [leftEdge, 0, 1, 2],
  topRules: {"File":[0,1]},
  tokenPrec: 0,
  termNames: {"0":"⚠","1":"@top","2":"Shebang","3":"Prolog","4":"Entry","5":"Key","6":"Comment","7":"Text","8":"Epilog","9":"Dict","10":"List","11":"(margin line peek)+","12":"Entry+","13":"value+","14":"␄","15":"peek","16":"indent","17":"dedent","18":"epilog","19":"margin","20":"\"#!\"","21":"flow","22":"line","23":"\"#\"","24":"\"//\"","25":"\"@\"","26":"eol","27":"value","28":"\"<>\"","29":"\"{}\"","30":"\"[]\"","31":"\"\\n\""}
})
