// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {terms} from "./lexical.ts"
import {margin} from "./context.ts"
import {highlight} from "./properties.ts"
export const parser = LRParser.deserialize({
  version: 14,
  states: ",YOqQTOOOxQSO'#CeO}QSO'#CfO!SQSO'#ChO!XQSO'#C}O!^QSO'#C}O!cQSO'#C}O!hQSO'#C}O!mQSO'#C}O!rQTO'#CgO#aQTO'#CgOOQS'#Cp'#CpO#rQTOOQOQSOOO#rQTOOOVQTOOO#|QTO,59PO$kQTO,59QO%YQTO,59SO%nQTO,59iO%sQTO,59iO%xQTO,59iO%}QUO,59iOOQS,59i,59iO&]QSO'#CmOOQS,59R,59RO&bQTO,59ROOQS-E6n-E6nO'PQSO'#C|OOQS1G.k1G.kOOQS1G.l1G.lOOQS1G.n1G.nO'XQSO1G/TO'^QSO1G/TO'cQSO1G/TOOQS'#Cn'#CnO'hQUO1G/TO$kQTO,59XOOQS1G.m1G.mOOQS'#Co'#CoO'sQSO,59hOOQS,59h,59hO'{QTO7+$oO(SQTO7+$oO(tQTO7+$oO)fQSO'#DUO)kQSO'#DUO)pQSO'#DUOOQS7+$o7+$oOOQS1G.s1G.sOOQS-E6m-E6mOOQS1G/S1G/SOOQS'#Ci'#CiOOQS<<HZ<<HZO)uQTO'#CjO*SQUO'#CkO'{QTO,59pO(SQTO,59pO(tQTO,59pOOQS,59U,59UO*hQTO,59UO*hQTO,59UO*rQUO'#ClOOQS'#Cq'#CqO+WQUO,59VOOQS,59V,59VO+WQUO,59VOOQS1G/[1G/[OOQS1G.p1G.pO+iQTO1G.pO+sQUO,59QO,XQUO,59pO,`QUO,59pO,wQUO,59pOOQS,59W,59WOOQS-E6o-E6oOOQS1G.q1G.qO-`QUO1G.qOOQS7+$[7+$[O+sQUO,59XOOQS7+$]7+$]O-qQSO'#CfO-vQSO'#CmO-{QSO'#DUO.QQSO'#DUO.VQSO'#DU",
  stateData: ".[~OkOS~OQWOUQOVROm]OrSOtTOvUO|VO~OoPO~PVOP`O~OPaO~OPbO~ORcO~OSdO~OTeO~OlfO~OPgO~OUhOQZXVZXmZXrZXtZXvZX|ZXgZX~OQWOrSOtTOvUO|VO~OVROm]O~P#aOhlOQpPUpPVpPmpPrpPtpPvpP|pP~OhlOQpPVpPmpPrpPtpPvpP|pPgpP~OhlOQpPrpPtpPvpP|pP~OspO~OuqO~OwrO~OhlOypPzpP{pP~OPuO~OUhOQZaVZamZarZatZavZa|ZagZa~OPwOgyO~OlzO~Ol{O~Ol|O~Oy}Oz!OO{!PO~OPwOg!TO~OgpP~P#|Oi!WOQ^PU^PV^Pm^Pr^Pt^Pv^P|^Pg^P~Oj!XOQ_PU_PV_Pm_Pr_Pt_Pv_P|_Pg_P~Ol!YO~Ol!ZO~Ol![O~OUQOVROg!]O~P#aOP!`OU!sOg!cOy!uOz!vO{!wO~OVROg!fO~P#aOU!tOP`Xg`Xy`Xz`X{`X~OP!`Og!nOy!uOz!vO{!wO~OVROg!pO~P#aOhlOPpPgpPypPzpP{pP~OUpP~P+sOi!WOP^PU^Pg^Py^Pz^P{^P~Oj!XOP_PU_Pg_Py_Pz_P{_P~OP!`Og!rOy!uOz!vO{!wO~OP!hO~OP!qO~Ol!iO~Ol!jO~Ol!kO~O",
  goto: "%UyPPPPPPPPPz}!X!c!m!t!{#S#Y#c#f#l#|PPPPPPPPPP$W$nPPPPPP${R_OS^O_Q!_!WR!d!XaZO[^_!W!^!_!gaYO[^_!W!^!_!gQ!VzT!e!Y!iQ!V{T!e!Z!jQ!V|T!e![!kX!a!X!b!d!oQiXQvjR!l!`RtfQxlR!SxU[O^_Uk[!^!gQ!^!WR!g!_Q!b!XS!m!b!oR!o!dQm`Sna!hQobQsfS!Ru!qV!Uz!Y!i`XO[^_!W!^!_!gRjYQ!QtX!`!X!b!d!o",
  nodeNames: "⚠ Line KeyEquals KeyText KeyDict KeyList Hash Slashes File Shebang Prolog Entry Comment Text Dict List Item Epilog KeyLong",
  maxTerm: 44,
  context: margin,
  propSources: [highlight],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "#T~RWstk!^!_v!`!a!T!b!c!Y!}#O!_#P#Q!l#o#p!q#q#r#O~nPqrq~vOo~R{PrP!`!a!OQ!TOyQ~!YOs~~!_O|~R!dPvP#P#Q!gQ!lO{Q~!qOw~R!vPtP#q#r!yQ#OOzQ~#TOu~",
  tokenizers: [0, 1, terms],
  topRules: {"File":[0,8]},
  tokenPrec: 0,
  termNames: {"0":"⚠","1":"Line","2":"KeyEquals","3":"KeyText","4":"KeyDict","5":"KeyList","6":"Hash","7":"Slashes","8":"@top","9":"Shebang","10":"Prolog","11":"Entry","12":"Comment","13":"Text","14":"Dict","15":"List","16":"Item","17":"Epilog","18":"KeyLong","19":"Line+","20":"Entry+","21":"Item+","22":"␄","23":"dedent","24":"indentT","25":"indentD","26":"indentL","27":"margin","28":"eol","29":"eof","30":"%mainskip","31":"\"#!\"","32":"text","33":"keyValue","34":"\"<\"","35":"\">\"","36":"\"{\"","37":"\"}\"","38":"\"[\"","39":"\"]\"","40":"value","41":"\"<>\"","42":"\"{}\"","43":"\"[]\"","44":"\"@\""}
})
