// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {terms} from "./lexical.ts"
import {margin} from "./context.ts"
import {highlight} from "./properties.ts"
export const parser = LRParser.deserialize({
  version: 14,
  states: ",fQqQTOOOxQSO'#CcO}QSO'#CdO!SQSO'#CfO!XQSO'#C|O!^QSO'#C|O!cQSO'#C|O!hQSO'#C|O!mQSO'#C|O!rQTO'#C|O!wQTO'#CeO#iQTO'#CeOOQS'#Cn'#CnQ#}QTOOQ#}QTOOQVQTOOO$UQTO,58}O$vQTO,59OO%hQTO,59QO&PQTO,59hO&UQTO,59hO&ZQTO,59hO&`QUO,59hOOQS,59h,59hO&nQSO,59hO&sQSO'#CkOOQS,59P,59PO&xQTO,59POOQS-E6l-E6lO'jQSO'#CyOOQS1G.i1G.iOOQS1G.j1G.jOOQS1G.l1G.lO'rQSO1G/SO'wQSO1G/SO'|QSO1G/SOOQS'#Cl'#ClO(RQUO1G/SOOQS1G/S1G/SO$vQTO,59VOOQS1G.k1G.kOOQS'#Cm'#CmO(^QSO,59eOOQS,59e,59eO(fQTO7+$nO(mQTO7+$nO)bQTO7+$nO*VQSO'#DTO*[QSO'#DTO*aQSO'#DTOOQS7+$n7+$nOOQS1G.q1G.qOOQS-E6k-E6kOOQS1G/P1G/POOQS'#Cg'#CgOOQS<<HY<<HYO*fQTO'#ChO*mQUO'#CiO(fQTO,59oO(mQTO,59oO)bQTO,59oOOQS,59S,59SO+RQTO,59SO+RQTO,59SO+]QUO'#CjOOQS'#Co'#CoO+qQUO,59TOOQS,59T,59TO+qQUO,59TOOQS1G/Z1G/ZOOQS1G.n1G.nO,SQTO1G.nO,^QUO,59OO,rQUO,59oO,yQUO,59oO-bQUO,59oOOQS,59U,59UOOQS-E6m-E6mOOQS1G.o1G.oO-yQUO1G.oOOQS7+$Y7+$YO,^QUO,59VOOQS7+$Z7+$ZO.[QSO'#CdO.aQSO'#CkO.fQSO'#DTO.kQSO'#DTO.pQSO'#DT",
  stateData: ".u~OjOS~OQXOnQOoROqSOsTOuUO{VO|WO~OlPO~PVOP`O~OPaO~OPbO~ORcO~OSdO~OTeO~OefO~OPgO~O|hO~OniOQXXdXXoXXqXXsXXuXX{XX|XXfXX~OQXOqSOsTOuUO{VO|WO~OoRO~P#iOgmOQmPdmPnmPomPqmPsmPumP{mP|mP~OgmOQmPdmPomPqmPsmPumP{mP|mPfmP~OgmOQmPqmPsmPumP{mP|mP~OrqO~OtrO~OvsO~OgmOxmPymPzmP~OPvO~OPwO~OniOQXadXaoXaqXasXauXa{Xa|XafXa~OPyOf{O~Oe|O~Oe}O~Oe!OO~Ox!POy!QOz!RO~OPyOf!VO~OfmP~P$UOh!YOQ[Pd[Pn[Po[Pq[Ps[Pu[P{[P|[Pf[P~Oi!ZOQ]Pd]Pn]Po]Pq]Ps]Pu]P{]P|]Pf]P~Oe![O~Oe!]O~Oe!^O~Of!_O~PVOP!bOf!eOn!uOx!wOy!xOz!yO~Of!hOoRO~P#iOn!vOP^Xf^Xx^Xy^Xz^X~OP!bOf!pOx!wOy!xOz!yO~Of!rOoRO~P#iOgmOPmPfmPxmPymPzmP~OnmP~P,^Oh!YOP[Pf[Pn[Px[Py[Pz[P~Oi!ZOP]Pf]Pn]Px]Py]Pz]P~OP!bOf!tOx!wOy!xOz!yO~OP!jO~OP!sO~Oe!kO~Oe!lO~Oe!mO~O",
  goto: "%TxPPPPPPPy|!W!b!l!s!z#R#X#b#e#k#{PPPPPPPPP$VPP$mPPPPPP$zR_OS^O_Q!a!YR!f!Za[O]^_!Y!`!a!iaZO]^_!Y!`!a!iQ!X|T!g![!kQ!X}T!g!]!lQ!X!OT!g!^!mX!c!Z!d!f!qQjYQxkR!n!bRufQzmR!UzU]O^_Ul]!`!iQ!`!YR!i!aQ!d!ZS!o!d!qR!q!fQn`Soa!jQpbQtfS!Tw!sV!W|![!k`YO]^_!Y!`!a!iRkZQ!SuX!b!Z!d!f!q",
  nodeNames: "⚠ Line KeyShort KeyText KeyDict KeyList File Shebang Prolog Entry Comment Text Dict List Item Epilog KeyLong",
  maxTerm: 44,
  context: margin,
  propSources: [highlight],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "#m~RYstq!P!Q!O!^!_!Z!_!`!h!`!a!m!b!c!r!}#O!w#P#Q#U#o#p#Z#q#r#h~vPn~qry~!OOl~~!RP!P!Q!U~!ZOo~R!`PqP!`!a!cQ!hOxQ~!mO|~~!rOr~~!wO{~R!|PuP#P#Q#PQ#UOzQ~#ZOv~R#`PsP#q#r#cQ#hOyQ~#mOt~",
  tokenizers: [0, 1, terms],
  topRules: {"File":[0,6]},
  tokenPrec: 0,
  termNames: {"0":"⚠","1":"Line","2":"KeyShort","3":"KeyText","4":"KeyDict","5":"KeyList","6":"@top","7":"Shebang","8":"Prolog","9":"Entry","10":"Comment","11":"Text","12":"Dict","13":"List","14":"Item","15":"Epilog","16":"KeyLong","17":"Line+","18":"Entry+","19":"Item+","20":"␄","21":"eol","22":"dedent","23":"indentT","24":"indentD","25":"indentL","26":"margin","27":"%mainskip","28":"\"#!\"","29":"text","30":"\"#\"","31":"\"//\"","32":"keyValue","33":"\"<\"","34":"\">\"","35":"\"{\"","36":"\"}\"","37":"\"[\"","38":"\"]\"","39":"value","40":"\"<>\"","41":"\"{}\"","42":"\"[]\"","43":"\"@\"","44":"\"=\""}
})
