// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  peek = 16,
  no_epi = 17,
  indent = 18,
  dedent = 19,
  margin = 20,
  epi_mar = 21,
  File = 1,
  Shebang = 2,
  Prolog = 3,
  Entry = 4,
  Key = 5,
  Comment = 6,
  Text = 7,
  Epilog = 8,
  Dict = 9,
  List = 10
