// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  peek = 15,
  indent = 16,
  dedent = 17,
  epilog = 18,
  margin = 19,
  File = 1,
  Shebang = 2,
  Prolog = 3,
  Entry = 4,
  Key = 5,
  Comment = 6,
  Text = 7,
  Epilog = 8,
  Dict = 9,
  List = 10
