lints = { workspace = true }

[package]
name = "tindalwic-cli"
description = "do tindalwic things from the shell"
version = { workspace = true }
edition = { workspace = true }
rust-version = "1.90"
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bumpalo = { workspace = true }
clap = { workspace = true, features = ["derive"] }
rand = { workspace = true }
time = { workspace = true, features = ["formatting"] }
tindalwic = { path = "../core", features = ["bumpalo"] }
tindalwic-serde = { path = "../serde" }
tree-sitter-cli = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
toml_edit = { workspace = true, features = ["serde"] }
yaml_serde = { workspace = true }
